
server:
  port: 8762


eureka:
  instance:
    #hostname: peer1
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: eurka-server